FROM python:3.11

WORKDIR /app

RUN pip install --upgrade pip setuptools wheel

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY emisor.py .
COPY templates.py .

EXPOSE 8000

CMD ["uvicorn", "emisor:app", "--host", "0.0.0.0", "--port", "8000"]